/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        lounge: {
          primary: "var(--color-primary)",
          secondary: "var(--color-secondary)",
          accent: "var(--color-accent)",
          bg: "var(--color-bg)",
          glass: "var(--color-glass)",
          text: "var(--color-text)",
          textSecondary: "var(--color-text-secondary)",
          border: "var(--color-border)",
          shadow: "var(--color-shadow)",
          glow: "var(--color-glow)",
        },
        midnight: {
          50: "#f0f1ff",
          100: "#e5e7ff",
          200: "#cdd2ff",
          300: "#a5aeff",
          400: "#7a7fff",
          500: "#5951ff",
          600: "#4733ff",
          700: "#3d22eb",
          800: "#321cc4",
          900: "#2a1a9e",
          950: "#0a0a1f",
        },
        electric: {
          50: "#faf5ff",
          100: "#f3e8ff",
          200: "#e9d5ff",
          300: "#d8b4fe",
          400: "#c084fc",
          500: "#a855f7",
          600: "#9333ea",
          700: "#7e22ce",
          800: "#6b21a8",
          900: "#581c87",
          950: "#3b0764",
        },
        cyan: {
          50: "#ecfeff",
          100: "#cffafe",
          200: "#a5f3fc",
          300: "#67e8f9",
          400: "#22d3ee",
          500: "#06b6d4",
          600: "#0891b2",
          700: "#0e7490",
          800: "#155e75",
          900: "#164e63",
          950: "#083344",
        },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Quicksand", "system-ui", "sans-serif"],
        rounded: ["Nunito", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "Consolas", "monospace"],
        serif: ["Playfair Display", "Georgia", "serif"],
      },
      borderRadius: {
        chill: "24px",
        "chill-lg": "32px",
        "chill-xl": "40px",
        soft: "40px",
        sharp: "4px",
        minimal: "8px",
      },
      backdropBlur: {
        glass: "20px",
        "glass-lg": "30px",
        minimal: "5px",
      },
      boxShadow: {
        glass: "0 8px 32px 0 rgba(31, 38, 135, 0.37)",
        glow: "0 0 20px rgba(168, 85, 247, 0.4)",
        "glow-cyan": "0 0 20px rgba(6, 182, 212, 0.4)",
        float: "0 0 20px rgba(0, 0, 0, 0.3)",
        chill: "0 4px 30px rgba(0, 0, 0, 0.1)",
      },
      dropShadow: {
        glow: "0 0 8px rgba(168, 85, 247, 0.6)",
        "glow-cyan": "0 0 8px rgba(6, 182, 212, 0.6)",
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        gradient: "gradient 15s ease infinite",
        "bounce-soft": "bounce-soft 1s ease-in-out",
        typewriter: "typewriter 2s steps(40) 1s forwards",
        grain: "grain 8s steps(10) infinite",
        "fade-in-slow": "fadeInSlow 2s ease-in",
        "float-gentle": "floatGentle 4s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        gradient: {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
        "bounce-soft": {
          "0%, 100%": {
            transform: "scale(1)",
            animationTimingFunction: "cubic-bezier(0.8, 0, 1, 1)",
          },
          "50%": {
            transform: "scale(1.05)",
            animationTimingFunction: "cubic-bezier(0, 0, 0.2, 1)",
          },
        },
        typewriter: {
          "0%": { width: "0" },
          "100%": { width: "100%" },
        },
        grain: {
          "0%, 100%": { transform: "translate(0, 0)" },
          "10%": { transform: "translate(-5%, -5%)" },
          "20%": { transform: "translate(-10%, 5%)" },
          "30%": { transform: "translate(5%, -10%)" },
          "40%": { transform: "translate(-5%, 15%)" },
          "50%": { transform: "translate(-10%, 5%)" },
          "60%": { transform: "translate(15%, 0)" },
          "70%": { transform: "translate(0, 10%)" },
          "80%": { transform: "translate(-15%, 0)" },
          "90%": { transform: "translate(10%, 5%)" },
        },
        fadeInSlow: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        floatGentle: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
    },
  },
  plugins: [],
};
